title: Obsidian Tasks X Powered
description: Task management for Obsidian, X Powered
baseurl: '/obsidian-tasks-x' # the subpath of your site, e.g. /blog
url: 'https://sytone.github.io' # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

# Back to top link
back_to_top: true
back_to_top_text: 'Back to top'

# Aux links for the upper right navigation
aux_links:
  'Obsidian Tasks X Powered on GitHub':
    - '//github.com/sytone/obsidian-tasks-x'

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/sytone/obsidian-tasks-x' # the github URL for your repo
gh_edit_branch: 'tasks-x/main' # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: 'tree' # "tree" or "edit" if you want the user to jump into the editor immediately

# Build settings
remote_theme: just-the-docs/just-the-docs
heading_anchors: true
